### ISSUE TITLE
Se pierde el estilo en algunas páginas

### ISSUE THREAD

**Issue by laarranz** [ardillan/torlavega#3]
Al navegar fuera del sitio y luego volver se pierde el estilo de la web.

**Comment by ardillan** [comment]
¡Gracias Luis! He visto que, efectivamente, la página de `motivacion` pierde estilos cuando entras a ella. Probablemente tenga que ver con la carga del CSS.

**Comment by laarranz** [comment]
He notado que al cargar la página `motivacion` falta de agregar la siguiente linea al código:

`<link rel="stylesheet" type="text/css" href="/styles.bd6c185cbf28d86da61b.css">`

Agregándola en el `head` desde el inspector de elementos de Google Chrome, verás que tiene efecto. 

No sé muy bien como funciona internamente Gatsby, o si puede ser un problema relacionado con webpack, leyendo el código fuente he notado que también lo usas, por si te pueden dar alguna pista.

**Comment by ardillan** [comment]
Creo que el problema viene porque los estilos están implementados dentro de la página de [`index.js`](https://github.com/ardillan/torlavega/blob/master/src/pages/index.js).

Lo correcto en este caso sería utilizar un componente que se considere global y común en toda la aplicación. Un candidato podría podría ser [`layout.js`](https://github.com/ardillan/torlavega/blob/master/src/components/layout.js).

**Comment by ardillan** [comment]
He hecho un `build` cambiando de las importaciones de fichero. Aparentemente se distribuyen bien los estilos. 

¡Gracias por la ayuda Luis! 😃
