### ISSUE TITLE
Nuevo estilo al banner principal de Datos del ayuntamiento

### ISSUE THREAD

**Issue by ilsanchez** [ardillan/torlavega#6]
No da la sensación de ser interactivo, de hecho, en la primera visita a la web ni siquiera entré por que no me dio esa impresión. Tal vez una flecha flotante a la derecha o un sombreado ayude ha hacerlo más intuitivo.

**Comment by ardillan** [comment]
¡Gracias Iván! Tienes razón, a mí también me ha sucedido un par de veces. Voy a probar a dar un poco más de interactividad al banner.

¡Gracias por el apunte! 😄

**Comment by ardillan** [comment]
He añadido interactividad al banner principal. Creo que ahora tiene más fuerza y hace ver que es una elemento al que se le puede hacer clic.
