### ISSUE TITLE
El formulario de contacto no da feedback al hacer submit

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/torlavega#9]
Cuando haces submit el formulario de contacto no da feedback de si ha ido bien o mal la acción, da la sensación de no funcionar. Yo pondría el típico mensaje de "hemos recibido tu formulario", evidentemente, currado como tu sabeh.

**Comment by ardillan** [comment]
Es cierto, ahora mismo está integrado con Netlify. Creo que se le puede añadir un parámetro para que la redirección al hacer _submit_ vaya a una página en concreto.
